Repository matter-labs/block-explorer, pull requests merged in 2024-04, with the labels that each got.

#170 feat: new automation scope for tests on Contracts API + Tokens API
  packages/integration-tests/src/config.ts
  packages/integration-tests/src/constants.ts
  packages/integration-tests/src/helper.ts
  packages/integration-tests/tests/api/contracts.test.ts
  packages/integration-tests/tests/api/tokens.test.ts
Labels: automation

#229 test: remove extra symbols to avoid 404 pages redirection
  packages/testing-docs/docs/BE Tests/ Common /Header /id231 - Header - Common - External links SN icons.md
  packages/testing-docs/docs/BE Tests/ Common /Header /id705 - Header - Common - Artifacts Network Drop Down.md
  packages/testing-docs/docs/BE Tests/ Common /Networks navigation - Production/id565 - Networks navigation Prod - Common - Navigation to Sepolia.md
  packages/testing-docs/docs/BE Tests/ Common /Networks navigation - Production/id566 - Networks navigation Prod - Common - Navigation to Mainnet.md
  packages/testing-docs/docs/BE Tests/ Common /Networks navigation - Staging/id561 - Networks navigation Staging - Common - Navigation to Goerli Stage2.md
  packages/testing-docs/docs/BE Tests/ Common /Networks navigation - Staging/id562 - Networks navigation Staging - Common - Navigation to zkSync Era Testnet.md
  packages/testing-docs/docs/BE Tests/ Common /Networks navigation - Staging/id563 - Networks navigation Staging - Common - Navigation to Mainnet.md
Labels: documentation, automation

#235 test: new formatting for Pages - 404 + Account pages
  packages/testing-docs/docs/BE Tests/Pages/404 page /id586 - 404 page - Pages - Check error message for Search field.md
  packages/testing-docs/docs/BE Tests/Pages/404 page /id713 - 404 page - Pages - Artifacts.md
  packages/testing-docs/docs/BE Tests/Pages/404 page /id714 - 404 page - Pages - Redirection.md
  packages/testing-docs/docs/BE Tests/Pages/404 page /id715 - 404 page - Pages - Verify opening 404 page.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id244 - Acc page - Pages - hashes copying.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id259 - Acc page - Pages - Navigation.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id260 - Acc page - Pages - Artifacts Account info.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id261 - Acc page - Pages - Artifacts Balances.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id262 - Acc page - Pages - Artifacts Transactions.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id339 - Acc page - Pages - Accounts URL.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id367 - Acc page - Pages - L1 Redirection.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id380 - Acc page - Pages - Verify IN label.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id381 - Acc page - Pages - Verify OUT label.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id382 - Acc page - Pages - Verify SELF label.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id593 - Acc page - Pages - Verify hover state for Age field.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id800 - Acc page - Pages - Verify collapsed state for Balances.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id807 - Acc page - Pages - Artifacts Empty state.md
  packages/testing-docs/docs/BE Tests/Pages/Account  page/id928 - Acc page - Pages - Artifacts Transactions -  Transfers tab.md
  packages/testing-docs/static/img/Pages/404pages/id586_1.png
  packages/testing-docs/static/img/Pages/404pages/id586_2.png
  packages/testing-docs/static/img/Pages/404pages/id713_1.png
  packages/testing-docs/static/img/Pages/404pages/id715_1.png
  packages/testing-docs/static/img/Pages/404pages/id715_2.png
  packages/testing-docs/static/img/Pages/AccountsPage/id244_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id244_2.png
  packages/testing-docs/static/img/Pages/AccountsPage/id244_3.png
  packages/testing-docs/static/img/Pages/AccountsPage/id259_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id260_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id261_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id262_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id262_2.png
  packages/testing-docs/static/img/Pages/AccountsPage/id339_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id367_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id380_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id381_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id382_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id593_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id800_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id800_2.png
  packages/testing-docs/static/img/Pages/AccountsPage/id807_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id928_1.png
  packages/testing-docs/static/img/Pages/AccountsPage/id928_2.png
  packages/testing-docs/static/img/Pages/AccountsPage/id928_3.png
  packages/testing-docs/static/img/Pages/AccountsPage/id928_4.png
  packages/testing-docs/static/img/Pages/AccountsPage/id928_5.png
  packages/testing-docs/static/img/Pages/AccountsPage/id928_6.png
  packages/testing-docs/static/img/Pages/AccountsPage/id928_7.png
Labels: documentation

#236 test: new formatting for Pages - Block + Blocks pages
  packages/testing-docs/docs/BE Tests/Pages/Block page /id235 - Block page - Pages - Navigation Addresses.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id236 - Block page - Pages - Artifacts Left table.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id264 - Block page - Pages - Artifacts Right table.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id265 - Block page - Pages - Artifacts Block Transactions.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id266 - Block page - Pages - Hashes copying.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id368 - Block page - Pages - Redirection Addresses.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id553 - Block page - Pages - Redirection Hashes.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id554 - Block page - Pages - Verify hover state for links.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id555 - Block page - Pages - Artifacts Zero block state.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id567 - Block page - Pages - Verify icons for informational tooltips Left table.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id568 - Block page - Pages - Verify informational tooltips on hover Left table.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id569 - Block page - Pages - Verify icons for informational tooltips Right table.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id570 - Block page - Pages - Verify informational tooltips on hover Right table.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id594 - Block page - Pages - Verify hover state for Age field.md
  packages/testing-docs/docs/BE Tests/Pages/Block page /id752 - Block page - Pages - Navigation Block info table.md
  packages/testing-docs/docs/BE Tests/Pages/Blocks page /id245 - Blocks page - Pages - Artifacts.md
  packages/testing-docs/docs/BE Tests/Pages/Blocks page /id246 - Blocks page - Pages - Navigation.md
  packages/testing-docs/docs/BE Tests/Pages/Blocks page /id607 - Blocks page - Pages - Verify hover state for Age field.md
  packages/testing-docs/static/img/Pages/BlockPage/id235_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id235_2.png
  packages/testing-docs/static/img/Pages/BlockPage/id236_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id264_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id265_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id266_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id266_2.png
  packages/testing-docs/static/img/Pages/BlockPage/id266_3.png
  packages/testing-docs/static/img/Pages/BlockPage/id266_4.png
  packages/testing-docs/static/img/Pages/BlockPage/id266_5.png
  packages/testing-docs/static/img/Pages/BlockPage/id368_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id553_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id553_2.png
  packages/testing-docs/static/img/Pages/BlockPage/id553_3.png
  packages/testing-docs/static/img/Pages/BlockPage/id554_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id555_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id567_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id568_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id569_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id570_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id594_1.png
  packages/testing-docs/static/img/Pages/BlockPage/id752_1.png
  packages/testing-docs/static/img/Pages/BlocksPage/id245_1.png
  packages/testing-docs/static/img/Pages/BlocksPage/id245_2.png
  packages/testing-docs/static/img/Pages/BlocksPage/id607_1.png
Labels: documentation

#241 test: new formatting for Pages - Error Page +Dashboard pages part)
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id101 - Dashboard - Pages - Artifacts Latest Transactions.md
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id234 - Dashboard - Pages - Navigation.md
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id273 - Dashboard - Pages - Artifacts Network stats Testnet.md
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id274 - Dashboard - Pages - Artifacts Latest Batches.md
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id584 - Dashboard - Pages - Verify empty state enabling Latest Transactions.md
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id608 - Dashboard - Pages - Verify hover state for Age field.md
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id676 - Dashboard - Pages - Artifacts Network stats Mainnet.md
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id695 - Common - Check metadata of the page ENG.md
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id697 - Common - Check metadata of the page UA.md
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id792 - Dashboard - Pages - Timestamp copying.md
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id924 - Dashboard - Pages - Verify Error messages for empty state Blocks.md
  packages/testing-docs/docs/BE Tests/Pages/Dashboard - main page/id925 - Dashboard - Pages - Verify Error page messages for empty state Latest Transactions.md
  packages/testing-docs/docs/BE Tests/Pages/Error page /id372 - Error page - Pages - Artifacts.md
  packages/testing-docs/docs/BE Tests/Pages/Error page /id373 - Error page - Pages - Navigation.md
  packages/testing-docs/docs/BE Tests/Pages/Error page /id374 - Error page - Pages - Verify Error page enabling for Block page.md
  packages/testing-docs/docs/BE Tests/Pages/Error page /id375 - Error page - Pages - Verify Error page enabling for Transaction page.md
  packages/testing-docs/docs/BE Tests/Pages/Error page /id376 - Error page - Pages - Verify Error page enabling for Address page.md
  packages/testing-docs/static/img/Pages/DashboardPage/id101_1.png
  packages/testing-docs/static/img/Pages/DashboardPage/id273_1.png
  packages/testing-docs/static/img/Pages/DashboardPage/id274_1.png
  packages/testing-docs/static/img/Pages/DashboardPage/id584_1.png
  packages/testing-docs/static/img/Pages/DashboardPage/id584_2.png
  packages/testing-docs/static/img/Pages/DashboardPage/id608_1.png
  packages/testing-docs/static/img/Pages/DashboardPage/id608_2.png
  packages/testing-docs/static/img/Pages/DashboardPage/id676_1.png
  packages/testing-docs/static/img/Pages/DashboardPage/id695_1.png
  packages/testing-docs/static/img/Pages/DashboardPage/id695_2.png
  packages/testing-docs/static/img/Pages/DashboardPage/id695_3.png
  packages/testing-docs/static/img/Pages/DashboardPage/id695_4.png
  packages/testing-docs/static/img/Pages/DashboardPage/id792_1.png
  packages/testing-docs/static/img/Pages/DashboardPage/id792_2.png
  packages/testing-docs/static/img/Pages/DashboardPage/id924_1.png
  packages/testing-docs/static/img/Pages/DashboardPage/id925_1.png
  packages/testing-docs/static/img/Pages/ErrorPage/id372_1.png
  packages/testing-docs/static/img/Pages/ErrorPage/id374_1.png
  packages/testing-docs/static/img/Pages/ErrorPage/id375_1.png
  packages/testing-docs/static/img/Pages/ErrorPage/id376_1.png
Labels: documentation

#243 test: new formatting for Pages - TransactionsLogs + Maintenance + Tokens + Transactions pages part
  packages/testing-docs/docs/BE Tests/Pages/Account page/id244 - Acc page - Pages - hashes copying.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id259 - Acc page - Pages - Navigation.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id260 - Acc page - Pages - Artifacts Account info.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id261 - Acc page - Pages - Artifacts Balances.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id262 - Acc page - Pages - Artifacts Transactions.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id339 - Acc page - Pages - Accounts URL.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id367 - Acc page - Pages - L1 Redirection.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id380 - Acc page - Pages - Verify IN label.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id381 - Acc page - Pages - Verify OUT label.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id382 - Acc page - Pages - Verify SELF label.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id593 - Acc page - Pages - Verify hover state for Age field.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id800 - Acc page - Pages - Verify collapsed state for Balances.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id807 - Acc page - Pages - Artifacts Empty state.md
  packages/testing-docs/docs/BE Tests/Pages/Account page/id928 - Acc page - Pages - Artifacts Transactions -  Transfers tab.md
  packages/testing-docs/docs/BE Tests/Pages/Maintenance page /id364 - Maintenance page - Pages - Artifacts.md
  packages/testing-docs/docs/BE Tests/Pages/Maintenance page /id365 - Maintenance page - Pages - Redirection.md
  packages/testing-docs/docs/BE Tests/Pages/Maintenance page /id366 - Maintenance page - Pages - Verify Maintenance enabling.md
  packages/testing-docs/docs/BE Tests/Pages/Tokens page /id1873 - Tokens page - Pages - Redirection.md
  packages/testing-docs/docs/BE Tests/Pages/Tokens page /id249 - Tokens page - Pages - Artifacts.md
  packages/testing-docs/docs/BE Tests/Pages/Tokens page /id250 - Tokens page - Pages - Navigation.md
  packages/testing-docs/docs/BE Tests/Pages/Tokens page /id275 - Tokens page - Pages - Hashes copying.md
  packages/testing-docs/docs/BE Tests/Pages/Tokens page /id815 - Tokens page - Pages - Token list Mainnet.md
  packages/testing-docs/docs/BE Tests/Pages/Tokens page /id816 - Tokens page - Pages - Token list Testnet.md
  packages/testing-docs/docs/BE Tests/Pages/Transaction Logs Tab/id230 - Tx Logs - Pages - Artifacts.md
  packages/testing-docs/docs/BE Tests/Pages/Transaction Logs Tab/id256 - Tx Logs - Pages - Navigation.md
  packages/testing-docs/docs/BE Tests/Pages/Transaction Logs Tab/id257 - Tx Logs - Pages - Hashes copying.md
  packages/testing-docs/docs/BE Tests/Pages/Transaction Logs Tab/id258 - Tx Logs - Pages - Drop Down lists.md
  packages/testing-docs/docs/BE Tests/Pages/Transaction Logs Tab/id802 - Tx Logs - Pages - Pagination.md
  packages/testing-docs/docs/BE Tests/Pages/Transactions page/id247 - Txs page - Pages - Artifacts.md
  packages/testing-docs/docs/BE Tests/Pages/Transactions page/id248 - Txs page - Pages - Navigation.md
  packages/testing-docs/docs/BE Tests/Pages/Transactions page/id377 - Txs page - Pages - Verify IN label.md
  packages/testing-docs/docs/BE Tests/Pages/Transactions page/id379 - Txs page - Pages - Verify SELF label.md
  packages/testing-docs/docs/BE Tests/Pages/Transactions page/id596 - Txs page - Pages - Verify hover state for Age field.md
  packages/testing-docs/static/img/Pages/MaintenancePage/id1873_1.png
  packages/testing-docs/static/img/Pages/MaintenancePage/id249_1.png
  packages/testing-docs/static/img/Pages/MaintenancePage/id250_1.png
  packages/testing-docs/static/img/Pages/MaintenancePage/id364_1.png
  packages/testing-docs/static/img/Pages/MaintenancePage/id366_1.png
  packages/testing-docs/static/img/Pages/MaintenancePage/id815_1.png
  packages/testing-docs/static/img/Pages/MaintenancePage/id816_1.png
  packages/testing-docs/static/img/Pages/TransactionLogsPage/id230_1.png
  packages/testing-docs/static/img/Pages/TransactionLogsPage/id257_1.png
  packages/testing-docs/static/img/Pages/TransactionLogsPage/id258_1.png
  packages/testing-docs/static/img/Pages/TransactionLogsPage/id802_1.png
  packages/testing-docs/static/img/Pages/TransactionsPage/id247_1.png
  packages/testing-docs/static/img/Pages/TransactionsPage/id247_2.png
  packages/testing-docs/static/img/Pages/TransactionsPage/id247_3.png
  packages/testing-docs/static/img/Pages/TransactionsPage/id247_4.png
  packages/testing-docs/static/img/Pages/TransactionsPage/id377_1.png
  packages/testing-docs/static/img/Pages/TransactionsPage/id379_1.png
  packages/testing-docs/static/img/Pages/TransactionsPage/id596_1.png
Labels: documentation

#211 test: create autotest for negative cases Contract API
  packages/integration-tests/tests/api/contracts.test.ts
Labels: automation
